### ISSUE TITLE
Example on how to create lists

### ISSUE THREAD

**Issue by ecklf** [abdolence/slack-morphism-rust#124]
Couldn't get this to work with the `md!` macro. It would be nice to have an example included in client on how to achieve  that.

**Comment by ecklf** [comment]
This is what I would be aiming for:

![image](https://user-images.githubusercontent.com/8146736/176703022-fff460f0-a227-47ac-8c96-d859982ca9d1.png)

Right now I am doing `SlackSelectionBlock`s with `\n` and `\t` formatting, which doesn't feel great but does the job.

**Comment by abdolence** [comment]
Well, this is not the question to the library, more like to Slack:
https://api.slack.com/reference/surfaces/formatting#block-formatting

If you look at their own example there you will see the same:
https://app.slack.com/block-kit-builder/T03CH2V42#%7B%22blocks%22%3A%5B%20%20%7B%20%20%20%22type%22%3A%20%22section%22%2C%20%20%20%22text%22%3A%20%7B%20%20%20%20%22type%22%3A%20%22mrkdwn%22%2C%20%20%20%20%22text%22%3A%20%22%E2%80%A2%20Detective%20Chimp%5Cn%E2%80%A2%20Bouncing%20Boy%5Cn%E2%80%A2%20Aqualad%22%20%20%20%7D%20%20%7D%20%5D%7D

I'm aware that they also have undocumented rich text blocks nowadays, but since they aren't documented they are not supported by the library as well  (if you brave enough to there is SlackBlock::RichText() with `serde_json::Value` to test it :)

**Comment by ecklf** [comment]
Crazy they do the same hacky bits. Thanks for linking that, I was just interested if there was any better way. I'll close this as I am not interested in looking into undocumented things.
