### ISSUE TITLE
Upload binary files

### ISSUE THREAD

**Issue by cjyar** [abdolence/slack-morphism-rust#234]
Thanks for writing this library!

I'd like to use `files_upload` to upload a binary file, like a PDF or an image. But `SlackApiFilesUploadRequest.content` is `Option<String>` instead of `Option<Vec<u8>>`. Any suggested workaround?

It seems simple enough to switch the type of that field, but it would break compatibility.

**Comment by abdolence** [comment]
Hey, I think it is content as string because the uploading method used in the implementation was `application/x-www-form-urlencoded`, and there is some old library that doesn't support anything binary there.
It probably is worth trying to change uploading to `multipart/form-data` (Slack supports both of them). I can have a look a bit later, but of course, PR is also welcome :)

**Comment by abdolence** [comment]
I managed to allocate time to improve this today, just writing here to avoid duplicate work if you were looking into this.

**Comment by abdolence** [comment]
https://github.com/abdolence/slack-morphism-rust/releases/tag/v1.17.0

**Comment by cjyar** [comment]
Thanks! I'll try and test this tomorrow.

**Comment by cjyar** [comment]
Works great! Thanks.
