### ISSUE TITLE
What's the difference between event types

### ISSUE THREAD

**Issue by oren0e** [abdolence/slack-morphism-rust#87]
In the docs here https://slack-rust.abdolence.dev/socket-mode.html there are 3 "test_" functions that each use a different type for the `event` argument. What are the differences between them?
For example, if I want to catch a message event (when a message is being sent in the channel), should I use `SlackPushEventCallback -> SlackEventCallbackBody -> SlackMessageEvent` or `SlackInteractionMessageActionEvent -> SlackHistoryMessage -> SlackMessageContent`?
Same question for catching app mentions (when someone mentions the app like `@bot_name`).
What are the differences between interaction, command, and push events?

**Comment by abdolence** [comment]
This separation is coming form Slack API itself. You can read details about that here:
https://api.slack.com/interactivity#events

Answering quickly to your particular questions:
`SlackPushEventCallback` -> is when you receive events in your workspace for new messages usually using this.

`SlackInteractionMessageActionEvent` happens when a user starts interacting with messages (for example clicking in buttons on messages.

Command events - when a user send a command to your bot. 

They all configured in different places in api.slack.com for your app.
